f2fs-tools: release 1.7.0
commit 61b738edf2e35e1a5ca04b2f5cee231b08d0f3ce
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Thu Jul 28 13:10:46 2016 -0700

    f2fs-tools: release 1.7.0

    This version adds Host-managed SMR detection code.

    libf2fs_format_la
     - changed its body

    libf2fs_la
     - added zbc_scsi_report_zones()

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 5c75ef097cd93be28c3c757da9dfa30879d0fa1a
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Fri Jul 15 10:27:23 2016 -0700

    fsck: recover symlink with zero i_size

    If we have i_blocks, we can recover i_size.

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit e98e6b6ad5e85caa428c6b9e3c3cb52409bbe1b5
Author: Xue Liu <liuxueliu.liu@huawei.com>
Date:   Fri Jul 15 20:01:25 2016 +0800

    fsck.f2fs: clean up duplicated code

    Call current_nat_addr() to calculate nat block address.

    Signed-off-by: Xue Liu <liuxueliu.liu@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 3f8406afb22e7e7799491703628ff3a3e9c470b9
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Fri Jul 15 20:01:24 2016 +0800

    f2fs-tools: update the format of output message

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit ff3e5e67a0e538a6670dc81672ec2b3bf85e7da3
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Fri Jul 15 20:01:23 2016 +0800

    fsck.f2fs: free nat entry cache

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit c95b427723803698359f970e75a56e607e9502dc
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Fri Jul 15 20:01:22 2016 +0800

    fsck.f2fs: fix typo

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit e55f79b483afbf4f6257ef616fc20b104c04e08a
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Fri Jul 15 20:01:21 2016 +0800

    fsck.f2fs: correct variable type and name

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 7119dc3c0ff0ced25197d01a4faa45ffd0141218
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Fri Jul 15 20:01:20 2016 +0800

    f2fs.fsck: fix endianess

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit a0ad1bead79fab381b0c5f7c9031dbe96609f38e
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Fri Jul 15 20:01:19 2016 +0800

    dump.f2fs: show inode->i_dir_level

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 9a5f225b3ae0cc5b8ebfd60d1de5a7459bc136c8
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Thu Jun 16 14:39:18 2016 -0700

    mkfs: define DISCARD/SECDISCARD macro

    If SECDISCARD/DISCARD is not defined, we can set it.
    In Android, we must set -DWITH_BLKDISCARD to discard the partition.

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit a85923eff79c04e6fa6258804afcbfe8a640299e
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Mon Jun 13 09:36:38 2016 -0700

    mkfs/fsck: add host-managed smr feature

    This feature flag will be used by f2fs to detect HMSMR device.

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit a8a59e01064685ee2b553ac4bc893e345d2ffb13
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Thu Jun 9 14:16:18 2016 -0700

    fsck.f2fs: allow zero link count for orphan inode

    This will be zeroed by f2fs during the mount time.

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit e7edc7c7c9bca62a1af90028338f3f8f2309b8c3
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Fri May 27 14:20:43 2016 -0700

    mkfs.f2fs: ZBC device support

    This patch adds "-m" option to configure ZBC device.

    This is to support host-managed SMR device and configure some major features
    and on-disk layout in f2fs.

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 590c150193176a630cbbbb2694746d688c6b1e0b
Author: Yunlei He <heyunlei@huawei.com>
Date:   Sat Jun 4 18:03:56 2016 +0800

    fsck.f2fs: modify sit dump && add nat dump

    modify sit dump && add nat dump like this:

    dump_sit:

    segment_type(0:HD, 1:WD, 2:CD, 3:HN, 4:WN, 5:CN)

    segno:      13  vblocks:512     seg_type:2      sit_pack:2

      ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff
      ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff
      ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff
      ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff

    dump_nat:

    nid:    3       ino:    3       offset:    0    blkaddr:   2076417      pack:2
    nid: 1042       ino: 1042       offset:    0    blkaddr:   2087156      pack:2
    nid:57076       ino:57076       offset:    0    blkaddr:   2071232      pack:2
    nid:57118       ino:57118       offset:    0    blkaddr:   2071233      pack:2
    Signed-off-by: Yunlei He <heyunlei@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit f35525ecf35469b03ccce6389df127e16839c8f1
Author: Yunlei He <heyunlei@huawei.com>
Date:   Wed May 18 18:00:37 2016 +0800

    fsck.f2fs: check sector size if formatted from a regular file

    This patch check sector size if formatted from a regular file,
    write the sector info to superblock from device info.

    Signed-off-by: Yunlei He <heyunlei@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 20d2b0ddd6e163a1fe8feba03085c015ef2df4cc
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Tue May 3 16:58:57 2016 -0700

    fsck.f2fs: reset fsck flag if there is no bug

    Let's update checkpoint, if fsck is set without any bug.

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 7973b19105433caa1b8bd3e901530f37cbc08191
Author: Junling Zheng <zhengjunling@huawei.com>
Date:   Tue Apr 26 10:23:32 2016 +0800

    fsck.f2fs: remove duplicated codes in sanity_check_raw_super

    Remove duplicated codes in sanity_check_raw_super().

    Signed-off-by: Junling Zheng <zhengjunling@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit de4d718886d452762fec1c3693c9cbe852b7b03f
Author: Yunlei He <heyunlei@huawei.com>
Date:   Tue Apr 26 13:25:08 2016 +0800

    resize.f2fs: replace the overprovision calculation method

    This patch replace the overprovision calculation method from
    mkfs tool.

    Signed-off-by: Yunlei He <heyunlei@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 94e352878c89d8f96f13d9deef28b012b0525d5d
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Wed Dec 16 16:47:23 2015 -0800

    script: add simple test script

    This patch adds a script to test sload.f2fs, defrag.f2fs, and resize.f2fs.

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 2598b1e18c9575113d98f0b7bf3786205ccf59e5
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Wed Dec 9 16:18:44 2015 -0800

    sload.f2fs: support loading files into partition directly

    This patch implements loading files into the existing partition.
    For example,
     # sload.f2fs -f ./ /dev/sdb1

    Then, all the directories and files will be loaded into /dev/sdb1.
    By default, newly files should have inline_data and inline_xattr, if possible.

    Signed-off-by: Hou Pengyang <houpengyang@huawei.com>
    Signed-off-by: Liu Shuoran <liushuoran@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit f6e8d5d65a7e1ee414f53f73ffc467bbe6115736
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Tue Dec 8 16:05:09 2015 -0800

    resize.f2fs: support to expand partition size

    Now user can expand existing partition with resize.f2fs.
    Currently, it doesn't support shrink an image.

    For example,
     # resize.f2fs -t [# of sectors] [image]

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit d66946430feee4687e7ce27941d863a3359fbd19
Author: Mike Frysinger <vapier@gentoo.org>
Date:   Mon Apr 18 18:19:53 2016 -0400

    fibmap: pull in sys/sysmacros.h for major/minor

    These funcs are provided by sys/sysmacros.h, so include the header
    directly.  Building with alternative C libraries can fail otherwise
    like so:

    fibmap.c: In function 'print_stat':
    fibmap.c:36:32: warning: implicit declaration of function 'major' [-Wimplicit-function-declaration]
      printf("dev       [%d:%d]\n", major(st->st_dev), minor(st->st_dev));
                                    ^
    fibmap.c:36:51: warning: implicit declaration of function 'minor' [-Wimplicit-function-declaration]
      printf("dev       [%d:%d]\n", major(st->st_dev), minor(st->st_dev));
                                                       ^
    fibmap.o: In function 'print_stat':
    tools/fibmap.c:36: undefined reference to 'minor'
    tools/fibmap.c:36: undefined reference to 'major'
    fibmap.o: In function 'stat_bdev':
    tools/fibmap.c:59: undefined reference to 'minor'
    tools/fibmap.c:59: undefined reference to 'major'

    Signed-off-by: Mike Frysinger <vapier@gentoo.org>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 8a864eb92b840d144f6c819eee3861ff48d0a175
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Wed Mar 23 11:50:39 2016 -0700

    fsck.f2fs: check sanity of superblock and fix any misalignment

    This patch detects any corrupted superblock and fix misalignment when it finds,
    which is synced with the f2fs kernel module.

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 6dccbf81467878f055246e49996a54563e4d10f5
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Wed Mar 23 11:19:20 2016 -0700

    fsck.f2fs: nullify the freed ckpt pointer

    Otherwise, we get a double free error by:

    In fsck/main.c,

    545 out_err:
    546         if (sbi->ckpt)
    547                 free(sbi->ckpt);

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit c9ca6922dfc4e89740004301579cd2c7c0f5cf66
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Mon Mar 14 14:16:59 2016 +0800

    fsck.f2fs: set fix_on if error is detected

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit daa3b079f3530028dc22543158f3ff8c4fda6649
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Mon Mar 14 14:16:57 2016 +0800

    fsck.f2fs: check ino in nat entry and node footer

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 8cd5f19940b225fae10406336a1fa02e194e22dd
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Mon Mar 14 14:16:55 2016 +0800

    fsck.f2fs: cache all nat entries and check each of them

    All nat entries are cached during building nat_area_bitmap, so that, in
    fsck_chk_meta, we can get and check blk_addr and ino directly, to see if
    they are in the valid range. Also, blk_addr is checked to see if the block
    is valid in sit's valid maps.

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 2b171c3e2bf2c9e26999ddfd436272867d40da39
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Mon Mar 14 14:16:54 2016 +0800

    fsck.f2fs: count the number of inodes during building nat_area_bitmap

    The nid and ino of an inode are the same. So during building
    nat_area_bitmap, we can know which nat entry represents an
    inode, thus, we can count the number of inodes.

    Then in fsck_chk_meta, the amount of inodes can be compared
    with that recorded in CP.

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 9dbe5576405d6733d094652bc2fb2dfe658d6df5
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Mon Mar 14 14:16:53 2016 +0800

    fsck.f2fs: introduce -p option to check meta

    This patch introduces a new option '-p' to do more checks on NAT/SIT areas.
    '-p' has 2 levels: level 1 has the same sematics as '-a'; level 2 checks
    NAT/SIT counters to see if they matches the status in SB and CP.

    A new function, fsck_chk_meta, is called by '-p 1' to implement these
    comparsion. If errors are detected, fix_on is set, which means fsck will
    do a 'fsck -f' immediately.

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

Also updated the Android.mk

Signed-off-by: mydongistiny <jaysonedson@gmail.com>